# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/viewer/set/background black
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add e-
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate -1
#
# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleB1
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/set/textColour red
#/vis/scene/add/text 0 -6 12 cm 25 7 1 CdTe
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/set/textColour black
#/vis/scene/add/text 6 12 2 cm 25 7 1 Shadow
#
# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
# "Envelope" is transparent blue to represent water
/vis/geometry/set/colour Envelope 0 1 1 1 0
#/vis/geometry/set/colour Collimator0 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator1 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator2 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator3 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator4 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator5 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator6 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator7 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator8 0 0 0.5 1.0 .7
#/vis/geometry/set/colour Collimator9 0 0 0.5 1.0 .7
/vis/geometry/set/colour Si 0 1 0 0 .5
/vis/geometry/set/colour CdTe 0 1 0 0 .5
/vis/geometry/set/colour CdTe0 0 1 0 0 .5
/vis/geometry/set/colour CdTe1 0 1 0 0 .5
/vis/geometry/set/colour CdTe2 0 1 0 0 .5
/vis/geometry/set/colour CdTe3 0 1 0 0 .5
/vis/geometry/set/colour CdTe4 0 1 0 0 .5
/vis/geometry/set/colour CdTe5 0 1 0 0 .5
/vis/geometry/set/colour CdTe6 0 1 0 0 .5
/vis/geometry/set/colour CdTe7 0 1 0 0 .5
/vis/geometry/set/colour CdTe8 0 1 0 0 .5
/vis/geometry/set/colour CdTe9 0 1 0 0 .5
#/vis/geometry/set/colour Shadow 0 1 1 0 .5
#/vis/geometry/set/colour Shadow2 0 0 1 0 .2
/vis/geometry/set/colour Shelf 0 0 1 0 .7
/vis/geometry/set/colour shield_pb 0 0 1 1 1.
/vis/geometry/set/colour shield_sn 0 0 1 0 .7
/vis/geometry/set/colour shield_cu 0 0.792 0.8824 1 1.
/vis/geometry/set/colour shield_al 0 1 1 0 .7
/vis/geometry/set/colour AlBaton 0 1 1 0 .7
/vis/geometry/set/colour Housing 0 1 1 0 .7
/vis/geometry/set/colour Bewindow 0 0 1 0 .7
/vis/geometry/set/colour Plastic 0 1 1 0 0.7
/vis/geometry/set/colour EPE 0 0.596 0.96 1 1.
/vis/geometry/set/colour KaptonTubs 0 0.8 1 0 .3
/vis/geometry/set/colour AirSample 0 0.3 1 1 .0
/vis/geometry/set/colour KaptonCover 0 0.8 1 0 .3
/vis/geometry/set/colour AlboxDown 0 1 1 1 0.3
/vis/geometry/set/colour Albox 0 1 1 1 0.3
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150

/vis/geometry/set/forceWireframe Housing 0 true
/vis/geometry/set/forceWireframe AlBaton 0 true
#/vis/geometry/set/forceSolid Housing 0 true

#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# trajectories color
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow 
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set e- green
/vis/modeling/trajectories/drawByParticleID-0/set neutron gray
/vis/modeling/trajectories/drawByParticleID-0/set mu+ red
/vis/modeling/trajectories/drawByParticleID-0/set mu- red

#/vis/set/textColour red
#/vis/scene/add/text 6 22 12 cm 25 7 1 mu-
#/vis/set/textColour green
#/vis/scene/add/text 6 16 12 cm 25 7 1 gamma
#/vis/set/textColour magenta
#/vis/scene/add/text 6 10 12 cm 25 7 1 e-
#/vis/set/textColour blue
#/vis/scene/add/text 6 4 12 cm 25 7 1 neutron

#default
#/vis/modeling/trajectories/drawByParticleID-0/set e- red
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
#/vis/modeling/trajectories/drawByParticleID-0/set pi+ magenta
#/vis/modeling/trajectories/drawByParticleID-0/set pi- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set pi0 magenta
# and everything else still grey


# trajectories smooth
/vis/scene/add/trajectories smooth
/vis/scene/add/trajectories smooth rich
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
