# must initialize
/run/initialize

#
#Next lines needed to have  atomic relaxation working 
#
/process/em/fluo true
/process/em/auger true

#
/control/verbose 2
/run/verbose 1
#
/gun/particle ion
/gun/ion 27 60
/run/beamOn 1

##
## rdm is only applied to the target volume
#/grdm/noVolumes
#/grdm/selectVolume Target
##
## place the isotopes in the middle of the target(source) 
#/gps/position 0 0 0	
#/gps/energy 0 keV	
#/gps/particle ion
#/gps/ion 92 238 0 0
#/run/beamOn 100000
#
