# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/viewer/set/background black
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add mu-
#/vis/filtering/trajectories/particleFilter-0/add e-
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate -1
#
# Decorations
# Name
/vis/set/textColour green
/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleB1
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
/vis/set/textLayout    # Revert to normal (left adjusted) layout
/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
/vis/scene/add/eventID # Drawn at end of event
/vis/scene/add/date    # Date stamp
#/vis/scene/add/logo2D  # Simple logo
#/vis/scene/add/logo    # 3D logo
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/set/textColour red
#/vis/scene/add/text 0 -6 12 cm 25 7 1 CdTe
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/set/textColour black
#/vis/scene/add/text 6 12 2 cm 25 7 1 Target
#
# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
# "Envelope" is transparent blue to represent water
/vis/geometry/set/colour Envelope 0 1 1 1 .3
/vis/geometry/set/colour CdTeUp 0 1 0 0 .9
/vis/geometry/set/colour intermediate1 0 1 0.98 0.80 .15
/vis/geometry/set/colour intermediate2 0 0.529 0.808 0.921 .15
/vis/geometry/set/colour Sample 0 0 1 0 1
/vis/geometry/set/colour VirTubs 0 1 1 0 0.5
/vis/geometry/set/colour VirTubs2 0 1 1 0 0.5
/vis/geometry/set/colour FoilTubs1 0 1 1 0 0.5
/vis/geometry/set/colour FoilTubs2 0 1 1 0 0.5
/vis/geometry/set/colour FoilTubs3 0 1 1 1 1
#/vis/geometry/set/colour BeWindowTubs 0 0 0.756 1 0.757 1
/vis/geometry/set/colour BeWindowTubs 0 1 1 0 0.5
/vis/geometry/set/colour Cover 0 0.608 0.188 1 .9
/vis/geometry/set/colour Window1 0 1 1 0 0.5
/vis/geometry/set/colour Window2 0 1 1 0 0.5
/vis/geometry/set/colour Window3 0 1 1 0 0.5
/vis/geometry/set/colour Window4 0 1 1 0 0.5
/vis/geometry/set/colour Window5 0 1 1 0 0.5
/vis/geometry/set/colour Window6 0 1 1 0 0.5
/vis/geometry/set/colour SnCover1 0 0 1 0 .9
/vis/geometry/set/colour SnCover2 0 0 1 0 .9
/vis/geometry/set/colour SnCover3 0 0 1 0 .9
/vis/geometry/set/colour SnCover4 0 0 1 0 .9
/vis/geometry/set/colour SnCover5 0 0 1 0 .9
/vis/geometry/set/colour SnCover6 0 0 1 0 .9
/vis/geometry/set/colour Crystal_Holder1 0 0.608 0.188 1 1
/vis/geometry/set/colour Crystal_Holder2 0 0.608 0.188 1 1
/vis/geometry/set/colour Crystal_Holder3 0 0.608 0.188 1 1
/vis/geometry/set/colour Crystal_Holder4 0 0.608 0.188 1 1
/vis/geometry/set/colour Crystal_Holder5 0 0.608 0.188 1 1
/vis/geometry/set/colour Crystal_Holder6 0 0.608 0.188 1 1
/vis/geometry/set/colour Deadlayer1 0 1 0 0 1
/vis/geometry/set/colour Deadlayer2 0 1 0 0 1 
/vis/geometry/set/colour Deadlayer3 0 1 0 0 1 
/vis/geometry/set/colour Deadlayer4 0 1 0 0 1 
/vis/geometry/set/colour Deadlayer5 0 1 0 0 1 
/vis/geometry/set/colour Deadlayer6 0 1 0 0 1 
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150

/vis/geometry/set/forceWireframe SSTubs 0 true
/vis/geometry/set/forceWireframe Chamber 0 true
/vis/geometry/set/colour Chamber 0 0 0.529 0.808 0.921 0.5
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

# trajectories color
/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set gamma magenta 
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set e+ green
/vis/modeling/trajectories/drawByParticleID-0/set e- green
/vis/modeling/trajectories/drawByParticleID-0/set neutron blue
/vis/modeling/trajectories/drawByParticleID-0/set mu+ red
/vis/modeling/trajectories/drawByParticleID-0/set mu- red

#/vis/set/textColour red
#/vis/scene/add/text 6 22 12 cm 25 7 1 mu-
#/vis/set/textColour green
#/vis/scene/add/text 6 16 12 cm 25 7 1 gamma
#/vis/set/textColour magenta
#/vis/scene/add/text 6 10 12 cm 25 7 1 e-
#/vis/set/textColour blue
#/vis/scene/add/text 6 4 12 cm 25 7 1 neutron

#default
#/vis/modeling/trajectories/drawByParticleID-0/set e- red
#/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
#/vis/modeling/trajectories/drawByParticleID-0/set proton cyan
#/vis/modeling/trajectories/drawByParticleID-0/set gamma green
#/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow
#/vis/modeling/trajectories/drawByParticleID-0/set pi+ magenta
#/vis/modeling/trajectories/drawByParticleID-0/set pi- magenta
#/vis/modeling/trajectories/drawByParticleID-0/set pi0 magenta
# and everything else still grey


# trajectories smooth
/vis/scene/add/trajectories smooth
/vis/scene/add/trajectories smooth rich
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
